export const ActionTypes = {
    LOGGED_IN_SUCCESS : "LOGGED_IN_SUCCESS",
    LOGOUT : "LOGOUT",
    ERROR_LOGIN : "ERROR_LOGIN",
    FETCH_ITEMS_SUCCESS : "FETCH_ITEMS_SUCCESS",
    FETCH_ITEMS_FAIL : "FETCH_ITEMS_FAIL",
    FETCH_POSTS_SUCCESS : "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_FAIL : "FETCH_POSTS_FAIL",
    FETCH_PROFILE_SUCCESS : "FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_FAIL : "FETCH_PROFILE_FAIL"
}